In [3]:
from datetime import date

# Get today's date
today = date.today()

# Print today's date
print("Today's date:", today)
type(today)

Today's date: 2024-05-23

datetime.date

In [1]:
import pickle

In [2]:
with open('Jupiter_works/dataset/finel_df.pkl','rb') as file:
    df = pickle.load(file)

In [10]:
df.head(1)

,id,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant_room,store_room,furnishing_type,luxury_category,floor_category,img,society,near_locatio
0,1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor,https://www.99acres.com/5-bhk-bedroom-independ...,smart world gems,"{'Genesis Hospital Sector 84': '2.2 Km', 'Dwar..."

In [16]:
df.society.values[100]

array(['dlf the ultima'], dtype=object)

In [14]:
# Assuming 'furnishing_type' is a column in the DataFrame df
unique_values_furnishing = (df['furnishing_type']).unique()

print(unique_values_furnishing)

AttributeError: 'DataFrame' object has no attribute 'unique'

In [1]:
import pandas as pd

In [6]:
pd.__version__

'2.0.3'

In [2]:
df=pd.read_csv('/home/veer/Desktop/Running_Projects/MatchMyMansion0/Jupiter_works/dataset/final_df.csv')

In [3]:
df.head()

,id,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant_room,store_room,furnishing_type,luxury_category,floor_category,img,society,near_locatio
0,1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor,https://www.99acres.com/5-bhk-bedroom-independ...,Smart World Gems,"{'Genesis Hospital Sector 84': '2.2 Km', 'Dwar..."
1,2,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,semifurnished,High,Mid Floor,https://www.99acres.com/5-bhk-bedroom-independ...,Bestech Park View Sanskruti,"{'Sapphire 93 Mall': '1.2 Km', 'Holiday Inn Se..."
2,3,flat,gwal pahari,7.50,4.0,4.0,3+,New Property,4842.0,1.0,0.0,semifurnished,Low,High Floor,https://www.99acres.com/4-bhk-bedroom-independ...,Paras Quartier,"{'Sector 55-56 Metro Station': '5 Km', 'Teri G..."
3,4,flat,sector 108,2.00,3.0,3.0,3+,Relatively New,2116.0,1.0,0.0,unfurnished,Medium,High Floor,https://www.99acres.com/3-bhk-bedroom-independ...,Experion The Heartsong,"{'Galleria 108 Mall': '0.65 Km', 'The Shikshiy..."
4,5,flat,sector 102,1.90,3.0,4.0,3,Relatively New,1710.0,1.0,0.0,unfurnished,High,Mid Floor,https://www.99acres.com/4-bhk-bedroom-independ...,Adani M2k Oyster Grande,{'Prime Scholars International School': '800 M...

In [7]:
df[df.society=='DLF The Primus']

Empty DataFrame
Columns: [id, property_type, sector, price, bedRoom, bathroom, balcony, agePossession, built_up_area, servant_room, store_room, furnishing_type, luxury_category, floor_category, img, society, near_locatio]
Index: []

In [5]:
df.id.values

array([   1,    2,    3, ..., 3552, 3553, 3554])

In [6]:
df[df['id']==5].society.dtype

dtype('O')

In [3]:
df.shape

(3554, 15)